### ISSUE TITLE
Intellisense breaks w/ a sufficiently large file

### ISSUE THREAD

**Issue by austinw-fineart** [wkillerud/some-sass#164]
The extension causes code navigation and refactoring among other features to become perpetually stuck on loading and no amount of waiting ever resolves this. Disabling the extension restores functionality; the built-in support seems to have no trouble with large files.

- VS Code version: 1.89.1
- Extension version: 3.1.4
- Operating system: Windows 11

Reproducible Case: https://github.com/telerik/kendo-themes

Steps to Reproduce:

1. Open @progress/kendo-theme-default/dist/all.scss
2. Try navigating to a variable

**Comment by wkillerud** [comment]
Hi, thanks for reporting! I downloaded https://unpkg.com/@progress/kendo-theme-default/dist/all.scss and can reproduce the problem.

The problem is caused by the large number of variables referencing other variables combined with the color decorator feature of the extension. I've not accounted for >9000 variables in the same document 😅 

As a temporary workaround you could turn off the color decorator setting in VS Code.

![](https://github.com/wkillerud/some-sass/assets/1223410/51aee14a-a4c6-4f12-a9d8-a50ecd564061)

**Comment by wkillerud** [comment]
Released in [3.1.5](https://github.com/wkillerud/some-sass/releases/tag/some-sass%403.1.5)
