### ISSUE TITLE
bug: suggestions shown from unimported packages

### ISSUE THREAD

**Issue by MenSeb** [wkillerud/some-sass#203]
Hello,

I am not sure if this is related to a specific package but I was able to reproduce the bug with sass-true since it exists in the repository.

There seems to have suggestions of the exports from sass-true even if it was not exported with the `@use` statement.

- VS Code version: 1.92.1
- Extension version: 3.5.0
- Operating system: Windows

Reproducible Case:

https://github.com/MenSeb/some-sass-bug/tree/main/src/bug-sass-true

Steps to Reproduce:

```scss
// _modules.scss
@forward "sass:color" as color-*;
@forward "sass:string" as string-*;
```

```scss
// index.scss
@use './modules' as *;

// It seems that the 'sass-true' package gets exposed.
// The packages color and string are correctly shown 
// under their prefix color- and string- from the @use.

// This works correctly and is shown in suggestions
@debug color-blue(#fff);
@debug string-unique-id();

// This is undefined and should not be shown in suggestions
@debug $catch-errors;
```

<img width="460" alt="image" src="https://github.com/user-attachments/assets/109f2119-8426-4c29-b714-b76a58182c33">

**Comment by wkillerud** [comment]
Huh, that's interesting! At first I thought it was because of the [suggest from use only](https://wkillerud.github.io/some-sass/user-guide/settings.html#only-include-suggestions-from-used-modules) setting, but even with that on I get the `$catch-errors` suggestion. 

It goes away if I comment out [this `@forward`](https://github.com/MenSeb/some-sass-bug/blob/faf884a04d3bd8ec56754005e5c8241f6d7c599d/src/_test.scss#L1) (and reload the window/restart VS Code), so somehow the suggestions code ends up there and follows the link to `sass-true` when it's not supposed to.

**Comment by wkillerud** [comment]
Turned out the server ignored user settings (oops!). From `3.6.1` [suggest from use only](https://wkillerud.github.io/some-sass/user-guide/settings.html#only-include-suggestions-from-used-modules) works as expected again, and you shouldn't see `$catch-errors` in this case.

**Comment by MenSeb** [comment]
Oh well actually on my side I forgot to use the `suggestFromUseOnly` option... nice catch anyway haha

Thanks it is now working as expected and I don't see the suggestions from `pkg:sass-true`.
